# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jOhWahDc4pF42ZiCp3l5yHTW04zv3Y_
"""

from types import EllipsisType
op = input("Escolha a operação (+, -, *, /): ")
a = float(input("Digite o primeiro número: "))
b = float(input("Digite o segundo número: "))

if op == "+":
    print("Resultado:", a + b)
elif op == "-":
    print("Resultado:", a - b)
elif op == "*":
    print("Resultado:", a * b)
elif op == "/":
    if b != 0:
        print("Resultado:", a / b)
    else:
        print("Erro: divisao por zero.")
else:
    print("Operacao invalida.")

input("Pressione Enter para sair...")
